from bson import ObjectId

muscle_groups = [
    {"_id": ObjectId(), "name": "Peitoral", "slug": "chest"},
    {"_id": ObjectId(), "name": "Costas", "slug": "back"},
    {"_id": ObjectId(), "name": "Ombros", "slug": "shoulders"},
    {"_id": ObjectId(), "name": "Bíceps", "slug": "biceps"},
    {"_id": ObjectId(), "name": "Tríceps", "slug": "triceps"},
    {"_id": ObjectId(), "name": "Quadríceps", "slug": "quadriceps"},
    {"_id": ObjectId(), "name": "Posterior", "slug": "hamstrings"},
    {"_id": ObjectId(), "name": "Glúteos", "slug": "glutes"},
    {"_id": ObjectId(), "name": "Panturrilha", "slug": "calves"},
    {"_id": ObjectId(), "name": "Abdômen", "slug": "core"},
]

# Build a lookup so exercises can reference groups by slug
_mg = {mg["slug"]: mg["_id"] for mg in muscle_groups}

exercises = [
    # Peitoral
    {
        "_id": ObjectId(),
        "name": "Supino Reto",
        "description": "Exercício de empurrar horizontal com barra, focado no peitoral maior.",
        "muscle_group_id": _mg["chest"],
        "difficulty": "intermediate",
        "equipment": "barbell",
    },
    {
        "_id": ObjectId(),
        "name": "Supino Inclinado com Halteres",
        "description": "Variação inclinada do supino para enfatizar a porção superior do peitoral.",
        "muscle_group_id": _mg["chest"],
        "difficulty": "intermediate",
        "equipment": "dumbbell",
    },
    {
        "_id": ObjectId(),
        "name": "Crucifixo",
        "description": "Movimento de adução horizontal com halteres, isolando o peitoral.",
        "muscle_group_id": _mg["chest"],
        "difficulty": "beginner",
        "equipment": "dumbbell",
    },
    {
        "_id": ObjectId(),
        "name": "Flexão de Braço",
        "description": "Exercício com o próprio peso corporal para peitoral, tríceps e ombros.",
        "muscle_group_id": _mg["chest"],
        "difficulty": "beginner",
        "equipment": "bodyweight",
    },
    {
        "_id": ObjectId(),
        "name": "Chest Press na Máquina",
        "description": "Pressão horizontal guiada por máquina, indicada para iniciantes.",
        "muscle_group_id": _mg["chest"],
        "difficulty": "beginner",
        "equipment": "machine",
    },
    # Costas
    {
        "_id": ObjectId(),
        "name": "Puxada Frontal",
        "description": "Movimento de puxar vertical para desenvolvimento do latíssimo do dorso.",
        "muscle_group_id": _mg["back"],
        "difficulty": "beginner",
        "equipment": "machine",
    },
    {
        "_id": ObjectId(),
        "name": "Remada Curvada com Barra",
        "description": "Remada horizontal com barra para espessura das costas.",
        "muscle_group_id": _mg["back"],
        "difficulty": "intermediate",
        "equipment": "barbell",
    },
    {
        "_id": ObjectId(),
        "name": "Remada Unilateral com Halter",
        "description": "Remada de um braço apoiado no banco para correção de assimetrias.",
        "muscle_group_id": _mg["back"],
        "difficulty": "beginner",
        "equipment": "dumbbell",
    },
    {
        "_id": ObjectId(),
        "name": "Barra Fixa",
        "description": "Exercício com peso corporal para costas e bíceps.",
        "muscle_group_id": _mg["back"],
        "difficulty": "advanced",
        "equipment": "bodyweight",
    },
    {
        "_id": ObjectId(),
        "name": "Levantamento Terra",
        "description": "Movimento composto de puxar do solo, recrutando posterior, costas e glúteos.",
        "muscle_group_id": _mg["back"],
        "difficulty": "advanced",
        "equipment": "barbell",
    },
    # Ombros
    {
        "_id": ObjectId(),
        "name": "Desenvolvimento com Halteres",
        "description": "Pressão vertical com halteres para deltoides anterior e medial.",
        "muscle_group_id": _mg["shoulders"],
        "difficulty": "intermediate",
        "equipment": "dumbbell",
    },
    {
        "_id": ObjectId(),
        "name": "Elevação Lateral",
        "description": "Isolamento do deltoide medial com halteres.",
        "muscle_group_id": _mg["shoulders"],
        "difficulty": "beginner",
        "equipment": "dumbbell",
    },
    {
        "_id": ObjectId(),
        "name": "Desenvolvimento Militar",
        "description": "Pressão vertical com barra em pé ou sentado.",
        "muscle_group_id": _mg["shoulders"],
        "difficulty": "intermediate",
        "equipment": "barbell",
    },
    # Bíceps
    {
        "_id": ObjectId(),
        "name": "Rosca Direta com Barra",
        "description": "Flexão de cotovelo com barra para hipertrofia do bíceps.",
        "muscle_group_id": _mg["biceps"],
        "difficulty": "beginner",
        "equipment": "barbell",
    },
    {
        "_id": ObjectId(),
        "name": "Rosca Alternada com Halteres",
        "description": "Flexão unilateral de cotovelo com supinação do antebraço.",
        "muscle_group_id": _mg["biceps"],
        "difficulty": "beginner",
        "equipment": "dumbbell",
    },
    {
        "_id": ObjectId(),
        "name": "Rosca Scott",
        "description": "Rosca apoiada no banco Scott para isolamento do bíceps.",
        "muscle_group_id": _mg["biceps"],
        "difficulty": "intermediate",
        "equipment": "machine",
    },
    # Tríceps
    {
        "_id": ObjectId(),
        "name": "Tríceps Pulley",
        "description": "Extensão de cotovelo no cabo para isolamento do tríceps.",
        "muscle_group_id": _mg["triceps"],
        "difficulty": "beginner",
        "equipment": "machine",
    },
    {
        "_id": ObjectId(),
        "name": "Tríceps Testa",
        "description": "Extensão de cotovelo deitado com barra, focado na cabeça longa do tríceps.",
        "muscle_group_id": _mg["triceps"],
        "difficulty": "intermediate",
        "equipment": "barbell",
    },
    {
        "_id": ObjectId(),
        "name": "Mergulho entre Bancos",
        "description": "Exercício com peso corporal para tríceps e peitoral inferior.",
        "muscle_group_id": _mg["triceps"],
        "difficulty": "beginner",
        "equipment": "bodyweight",
    },
    # Quadríceps
    {
        "_id": ObjectId(),
        "name": "Agachamento Livre",
        "description": "Movimento composto fundamental para quadríceps, glúteos e posterior.",
        "muscle_group_id": _mg["quadriceps"],
        "difficulty": "intermediate",
        "equipment": "barbell",
    },
    {
        "_id": ObjectId(),
        "name": "Leg Press",
        "description": "Pressão de pernas na máquina, variando o ângulo para diferentes recrutamentos.",
        "muscle_group_id": _mg["quadriceps"],
        "difficulty": "beginner",
        "equipment": "machine",
    },
    {
        "_id": ObjectId(),
        "name": "Cadeira Extensora",
        "description": "Isolamento do quadríceps em máquina de extensão.",
        "muscle_group_id": _mg["quadriceps"],
        "difficulty": "beginner",
        "equipment": "machine",
    },
    {
        "_id": ObjectId(),
        "name": "Avanço com Halteres",
        "description": "Movimento unilateral para quadríceps, glúteos e equilíbrio.",
        "muscle_group_id": _mg["quadriceps"],
        "difficulty": "intermediate",
        "equipment": "dumbbell",
    },
    # Posterior
    {
        "_id": ObjectId(),
        "name": "Mesa Flexora",
        "description": "Flexão de joelho em máquina para isolamento do bíceps femoral.",
        "muscle_group_id": _mg["hamstrings"],
        "difficulty": "beginner",
        "equipment": "machine",
    },
    {
        "_id": ObjectId(),
        "name": "Stiff",
        "description": "Levantamento terra com joelhos semiflexionados para posterior e glúteos.",
        "muscle_group_id": _mg["hamstrings"],
        "difficulty": "intermediate",
        "equipment": "barbell",
    },
    # Glúteos
    {
        "_id": ObjectId(),
        "name": "Hip Thrust",
        "description": "Extensão de quadril apoiado no banco para máximo recrutamento dos glúteos.",
        "muscle_group_id": _mg["glutes"],
        "difficulty": "intermediate",
        "equipment": "barbell",
    },
    {
        "_id": ObjectId(),
        "name": "Glúteo no Cabo",
        "description": "Extensão de quadril unilateral no cabo para isolamento dos glúteos.",
        "muscle_group_id": _mg["glutes"],
        "difficulty": "beginner",
        "equipment": "machine",
    },
    # Panturrilha
    {
        "_id": ObjectId(),
        "name": "Panturrilha em Pé",
        "description": "Elevação de calcanhar em pé para sóleo e gastrocnêmio.",
        "muscle_group_id": _mg["calves"],
        "difficulty": "beginner",
        "equipment": "machine",
    },
    {
        "_id": ObjectId(),
        "name": "Panturrilha Sentado",
        "description": "Elevação de calcanhar sentado com foco no sóleo.",
        "muscle_group_id": _mg["calves"],
        "difficulty": "beginner",
        "equipment": "machine",
    },
    # Abdômen
    {
        "_id": ObjectId(),
        "name": "Prancha",
        "description": "Isometria de core para estabilidade lombar e abdominal.",
        "muscle_group_id": _mg["core"],
        "difficulty": "beginner",
        "equipment": "bodyweight",
    },
    {
        "_id": ObjectId(),
        "name": "Abdominal Supra",
        "description": "Flexão de tronco para reto abdominal.",
        "muscle_group_id": _mg["core"],
        "difficulty": "beginner",
        "equipment": "bodyweight",
    },
    {
        "_id": ObjectId(),
        "name": "Abdominal na Polia",
        "description": "Flexão de tronco com resistência no cabo para maior sobrecarga.",
        "muscle_group_id": _mg["core"],
        "difficulty": "intermediate",
        "equipment": "machine",
    },
]
